---
- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-web-console-smoke-test-ansible-XXXXXX
  register: mktemp
  changed_when: False

- name: Copy files to temp directory
  copy:
    src: openshift-web-console-smoke-test.yaml
    dest: "{{ mktemp.stdout }}/openshift-web-console-smoke-test.yaml"

- name: Copy admin client config
  copy:
    src: "{{ openshift.common.config_base }}/master/admin.kubeconfig"
    dest: "{{ mktemp.stdout }}/admin.kubeconfig"
    remote_src: yes

- name: Apply the smoke test template
  shell: >
    {{ openshift_client_binary }} process -f "{{ mktemp.stdout }}/openshift-web-console-smoke-test.yaml"
    --param CONSOLE_URL="{{ openshift.master.public_console_url }}"
    --param IMAGE="{{ openshift_web_console_smoke_test_image }}"
    --param TEST_INTERVAL_MINUTES="{{ openshift_web_console_smoke_test_test_interval_minutes }}"
    | {{ openshift_client_binary }} apply --config={{ mktemp.stdout }}/admin.kubeconfig -f -

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
